### ISSUE TITLE
PDF Codeblocks appearance changed in recent update

### ISSUE THREAD

**Issue by JayaswalPrateek** [birneee/obsidian-adwaita-theme#10]
recent update to obsidian has forced all codeblocks in the exported .pdf to be rendered in light theme, regardless of the selected base color. 
Could you please make the relevant changes in .css to mitigate it and restore dark codeblocks?

**Comment by birneee** [comment]
Thanks for reporting this.
But isn't that something that should better be addressed by the obsidian team?
