### ISSUE TITLE
Strange spacing bug on Ubuntu 22.10, Obsidian 1.3.5

### ISSUE THREAD

**Issue by weavejester** [birneee/obsidian-adwaita-theme#12]
When I upgrade from version 0.2.0 of the theme to version 0.3.0, I'm getting an odd spacing issue:

![image](https://github.com/birneee/obsidian-adwaita-theme/assets/8780/579a692a-6a23-4727-8262-1be92d6e746c)

This appears to be caused by the "Noto Color Emoji" font, as when I remove that from the `--font-interface-theme` var, the text goes back to normal. The theme only uses this font as its second choice, so perhaps I've run into this because I don't have "Canterell" on my system for it to use as its first choice.

**Comment by ghost** [comment]
I also have the same issue on Pop OS, which is derived from Ubuntu.

As I'm not a technical guy, I don't want to go into var and delete any fonts. But a solution I found is to instead select another font in the appearance settings. A few lines below the area for selecting a theme, is a Font section to set an interface font or other font. Once I selected something as the interface font, it fixed this bug. I selected the 'Ubuntu' font but I presume it would work with many others.

![Obsidian Screenshot from 2023-08-11 18-54-47](https://github.com/birneee/obsidian-adwaita-theme/assets/142042001/1530eca9-cf5f-4a85-b71b-19385832e363)
