### ISSUE TITLE
Stacked tabs titlebar misalignment

### ISSUE THREAD

**Issue by TylerLaBree** [birneee/obsidian-adwaita-theme#6]
When in stacked tabs mode, a bit of the occluded tab peeks through between the foreground pane and its vertical side titlebar. There is also a bit of the occluded tab visible below the titlebar, which should normally extend all the way to the bottom.

This only occurs with Adwaita style tabs enabled.

![Screenshot from 2023-01-25 11-05-41](https://user-images.githubusercontent.com/51167014/214631307-76287f1f-4df3-4d3c-900c-1b322630a687.png)

**Comment by richardbowman** [comment]
Love this theme. I want it to be my goto. But this one is a pretty painful bug. @birneee are you planning on addressing this? I haven't dug into Obsidian theming enough to easily help submit a pull request, but if I was to do that, I'd want to make sure you are planning to actively make updates or accept changes anyhow?

**Comment by richardbowman** [comment]
Thank you!! Looks great!
